<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class LogoutController extends Controller
{
    //

    public function __construct()
    {
        $this->middleware('myAuth'); // TODO: Change the autogenerated stub
    }

    public function __invoke(Request $request){

        Auth::logout();
        return response()->json(null ,201) ;
    }
}
