<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;
use phpDocumentor\Reflection\Types\Self_;

class Step extends Model
{
    //
    protected $fillable =[
        'order','title','body','uuid'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function (Step $step){

            $step->uuid = Str::uuid();

            self::all()->where('snippet_id',$step->snippet->id)->each(function ($oldStep)use($step){
                if ($step->order <= $oldStep->order){
                    $oldStep->order = $oldStep->order + 1 ;

                    $oldStep->save();
                }
            });


        });
    }

    public function getRouteKeyName()
    {
        return 'uuid';
    }
    public function snippet(){
        return $this->belongsTo(Snippet::class) ;
    }
}
